spring:
  application:
    name: gateway

  config:
    import: "optional:consul:"

  cloud:
    consul:
      host: localhost
      port: 8500

    gateway:
      server:
        webflux:
          routes:
            - id: event
              uri: lb://event
              predicates:
                - Path=/api/event/**
            - id: vendor
              uri: lb://vendor
              predicates:
                - Path=/api/vendor/**

server:
  port: 8100

management:
  endpoints:
    web:
      exposure:
        include: "health,info"